exhibitionist-digital/ultra

src/render.ts
Note that this presumes we are always building UTF-8, which is a heck of a presumption.
=> Handle strings as well as Uint8Arrays in body; error if not either.

mod.ts, src/oak/handler.ts, src/types.ts
#43 
Adds a basic Oak middleware handler
=> oak handler

README.md, src/deno/build.ts, src/deno/server.ts, src/render.ts, src/server.ts, src/transform.ts, src/types.ts, workspace/importmap.json, workspace/src/app.jsx
#44 
This updates the React Web Stream handler, and also adds a cool new `renderToString` equivalent `ultra` stream bypass option.
=> new stream handler, and addition of renderToString

src/deno/build.ts, src/deps.dev.ts, src/deps.ts, src/importMapResolver.test.ts, src/preloader.ts, src/resolver.test.ts, src/transform.test.ts, src/vendor.ts
=> create deps.dev to ensure server start is speedy

src/env.ts, src/resolveEnv.test.ts, src/resolveEnv.ts
Using https://github.com/ianstormtaylor/superstruct to validate the environment is correct and coercing that result with defaults.
=> Env validate

src/env.ts
Helps with Intellisense and documentation!
=> added basic comments to env.ts

src/config.test.ts, src/config.ts, src/deps.dev.ts
This PR adds unit tests for `config.ts`.
=> Unit tests for config.ts

examples/with-react-router/server.tsx, examples/with-react-router/src/app.tsx, hooks/server-context.js, hooks/use-server-context.js, lib/deps.ts, lib/middleware/compiler.ts, lib/provider.ts, lib/types.ts, server.ts
Some WIP for use-server-context
=> hook: use-server-context

examples/with-preact/importMap.json
=> chore: preact and preact compat version

examples/ultra-website/content/docs.mdx
This adds documentation about how to use Middleware with **Ultra**.
A couple of small corrections were also done.
=> Added middleware doc

examples/with-material-ui/src/app.tsx
Made the Material UI button in the example more 'button-like' and added interactivity to it.
=> Improved MaterialUI button

examples/basic/client.tsx, hydrate.js
This PR is based on researching shopify/hydrogen and other various hydration strats. Will hydrate when browser is idle.
https://reactjs.org/docs/react-api.html#starttransition
=> feat: new recommended way of hydrating client

examples/basic/src/app.tsx, examples/react-expermimental/src/app.tsx, examples/ultra-website/content/docs.mdx, examples/with-islands/src/app.tsx, examples/with-material-ui/src/app.tsx, examples/with-preact/src/app.tsx, examples/with-service-worker/src/app.tsx, hooks/use-asset.js, lib/build/deps.ts, lib/build/ultra.ts, test/fixture/src/app.tsx, test/hooks/use-asset.test.tsx
This PR updates mesozoic to latest version
=> deps: updated mesozoic

examples/with-preact/importMap.json
update to use newest preact version
=> chore: preact bump version

lib/create/common/content/app.ts
=> fix: add useAsset to create script

lib/create/common/content/app.ts
=> create: add tw import to create script

.devcontainer/Dockerfile, lib/build/deps.ts, lib/build/types.ts, lib/build/ultra.ts, test/fixture/build.test.ts, test/fixture/src/app.tsx, test/fixture/src/components/Post.tsx
This PR should allow dynamic imports to be used on platforms like Deno Deploy
=> feat: inline server dynamic imports

lib/deps.ts, lib/types.ts
v2.5.1 fixes a really blocking issue, https://github.com/honojs/hono/issues/659.
=> chore: update Hono

lib/middleware/compiler.ts, lib/types.ts
Adds compile hooks to the compiler middleware of the dev server.
=> feat: add compile hooks to dev server

lib/create/modules/twind/index.ts
This allows modifying common configurations like `plugins` and `hash` with less refactoring.
=> chore(create): improve the configuration part in the twind module

lib/context/dataStream.ts, test/unit/use-async.test.tsx
=> fix: use Promise.allSettled to parallelise useAsync

lib/build/deps.ts
=> WASM dependencies are not cached

examples/basic/importMap.json, examples/bogus-marketing-or-blog/importMap.json, examples/lite/importMap.json, examples/react-expermimental/importMap.json, examples/ultra-website/importMap.json, examples/with-api-routes/importMap.json, examples/with-csr/importMap.json, examples/with-earthstar/importMap.json, examples/with-emotion/importMap.json, examples/with-esm/importMap.json, examples/with-fly-io/importMap.json, examples/with-islands/importMap.json, examples/with-mdx/importMap.json, examples/with-netlify-(WIP)/importMap.json, examples/with-preact/importMap.json, examples/with-react-helmet-async/importMap.json, examples/with-react-query/importMap.json, examples/with-react-router/importMap.json, examples/with-react-three-fiber/importMap.json, examples/with-service-worker/importMap.json, examples/with-stitches/importMap.json, examples/with-trpc/importMap.json, examples/with-twind/importMap.json, examples/with-unocss/importMap.json, examples/with-use-gesture/importMap.json, examples/with-wouter/importMap.json, lib/create/common/content/importMap.ts, lib/create/common/createUltraApp.ts, version.ts
Fixes the create script, previous released version didn't bump the version numbers. Closes #256
=> fix-create
