exhibitionist-digital/ultra

- examples/boilerplate/importmap.json
- examples/boilerplate/src/app.jsx
- examples/react18/importmap.json
- examples/react18/src/app.jsx
- examples/threejs/importmap.json
- examples/threejs/src/app.jsx
- examples/ultra-website/importmap.json
- examples/ultra-website/src/app.tsx
- examples/web3/importmap.json
- examples/web3/src/app.tsx
- importmap.json
- src/render.ts
The actual npm module is called "react-helmet". I did this to avoid confusion with the also popular npm module [helmet](https://github.com/helmetjs/helmet) (and because deno crashed on me after I tried to use it :P).
PS: Sorry for all the useless commits before the actual commit, I messed up. This PR should be merged after #28. I can also try to fix it somehow on this branch if it's too much hassle or if #28 takes longer or changes.
> replace `helmet` with `react-helmet`

- src/render.ts
I looked at most of the files in this project and couldn't find any real reason this `div` is included here. Maybe I'm missing something and the `id="ultra"` is actually important,
- if yes, then I'd suggest moving it to the `body` element, like `<body id="ultra">`
- if no, then I'd suggest merging this PR
Main inspiration for this was me being annoyed by this "in-between" element while styling my website through a global css file. It also kind of prevents me to follow HTML best practices, at least I think so. To be fair, after a short research I couldn't find anyone explicitly saying "use elements like `main` and `header` only as direct children of `body`"; it feels weird putting them inside a "generic" `div` though.
> Remove `div` inside `body`

- mod.ts
- src/oak/handler.ts
- src/render.ts
- src/server.ts
- src/types.ts
#42 
Not Fast Refresh™, but this allows a web socket connection to reload the page on changes.
Before v0.8.0 release we need to enable some options to enable/disable this.
> reload websocket

- src/server.ts
I would like to have the ability so serve API routes from the lambda / edge that ultra is deployed to. This removes the need to have a separate API deployment.
On line 73 I removed the slash between `"src"` and `pathname` because pathname always starts with a slash.
This PR assumes you want to use the `src/api` directory which might not be in line with the goals/visions of Ultra.
This would solve https://github.com/exhibitionist-digital/ultra/issues/51 .
> API Routes

- src/deno/build.ts
- src/deno/deps.ts
This fixes a bug with copying static assets on Deno Deploy
> copy static assets

- workspace/deno.json
As the React 18 TypeScript types have been [added to Definitely Typed](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210), there is no more need for the `--no-check` flag in the `deno.json` tasks.
> Removed no-check flag from deno.json tasks

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
I honestly can't live without this. For those developers that use it, we can lessen the burden of getting up and running for contributing to Ultra.
> dx: added devcontainer config for vscode

- src/vendor.ts
I like to use ?dev on my importMaps, this will remove it when vendoring those dependencies.
> vendor should remove dev param if it's set

- cache.js
This PR reflects the minimum scaffolding to fix #77.
Prior to this commit, the docs outline separately importing the 'cache' type from './src/types.ts' which requires statically defining the import rather than adding it to 'importMap.json'. @mashaal suggested using JSDoc to make the 'Cache' type known on import of 'cache.js' which eliminates the need to separately import it.
Rather than use the JSDoc import syntax, `Map` is [universally supported](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#browser_compatibility) so I opted to simply `@typedef` to avoid edge cases I'm not familiar with. It's been quite some time since I've dabbled with JS/TS/Deno, so please let me know if any changes are needed. Thank you!
> Add JSDoc comment for 'Cache' type

- src/deno/build.ts
- src/deps.ts
- src/resolver.test.ts
- src/resolver.ts
- src/server.ts
All the `ify` functions in `resolver.ts` have been replaced with a new function `replaceFileExt`. 
This work is done in support of issue #76
> Resolver refactor

- src/oak/handler.ts
- src/server.ts
- src/server/requestHandler.ts
- workspace/deno.json
- workspace/oak.ts
- workspace/tests/helpers.ts
- workspace/tests/workspace_home.test.ts
This PR moves a lot of duplicated code between the Deno native and Oak server implementations to a factory function
```ts
createRequestHandler(options: CreateRequestHandlerOptions) => ((request: Request) => Promise<Response>)
```
> Generic request handler

- deno.json
- src/unstable/README.md
- src/unstable/deps.ts
- src/unstable/server.ts
- src/unstable/types.ts
- unstable.ts
- workspace_unstable/deno.json
- workspace_unstable/importMap.json
- workspace_unstable/server.ts
- workspace_unstable/src/app.tsx
This PR introduces an entrypoint `unstable.ts` and a `workspace_unstable` which will export any experimental features, from `src/unstable`
This shouldn't affect any other PR's as it's all new code.
> Introduce unstable entrypoint and workspace

- src/ast/ultra.ts
- src/render.ts
- src/resolver.ts
- src/server/requestHandler.ts
- src/transform.ts
- src/types.ts
Only the app entry and API routes need cache-busting strategy, the other ESM doesn't seem to need it, so I've removed them. This makes the project a lot simpler, especially for preload headers.
> rm cachebuster for all files non-app entry and API

- .gitignore
- src/config.ts
- src/vendor.test.ts
- src/vendor.ts
This PR unit tests the `vendor.ts` file's `vendor` function.
FWIW, I ran the deno coverage tool on all our code (including this test) and here are the summary results:
> Added a unit test of `vendor.ts`

- src/ast/ultra.ts
- src/deno/server.ts
- src/render.ts
- src/server.ts
- src/server/requestHandler.ts
- src/types.ts
- src/unstable/server.ts
This removes the need for a `root` env to be set, mainly effects prod deployments, and should remove the need to set one for Deno Deploy.
> rm `root` from deno server and request handlers

- src/oak/handler.ts
- workspace/oak.ts
- workspace/tests/helpers.ts
- workspace/tests/workspace_home.test.ts
Fixes the issue where the server processes weren't closing due to using Deno.run with deno tasks, which was creating child processes.
Changes to Deno.run the server entrypoints directly.
> tests: Deno.run the actual entrypoint

- .github/workflows/deno.yml
- workspace/tests/helpers.ts
- workspace/tests/workspace_home.test.ts
This PR upgrades Puppeteer used in our e2e tests from v9.0.2 to v14.1.1
> chore: Upgrade Puppeteer 9.0.2->14.1.1

- CONTRIBUTING.md
- README.md
This PR updates CONTRIBUTING.md to add coding & naming standards. Styling recommendations are derived from [Deno Style Guide](https://deno.land/manual/contributing/style_guide).
**Note**: This is a very much a draft work-in-progress (WIP). Please suggest edits, additions or deletions.
This PR is support of issue #118 and PR #119 is related to our initial standards discussion in that issue.
> docs: Added coding & naming standards to CONTRIBUTING.md

- build.ts
- client.js
- examples/basic/src/app.tsx
- lib/build/assetManifest.ts
- lib/build/compileSources.ts
- lib/build/resolvePaths.ts
- lib/build/types.ts
- lib/build/utils/path.ts
- lib/client/asset.js
- lib/render.tsx
- lib/server.ts
- lib/ultra.ts
- lib/utils/hash.ts
This PR adds `asset-manifest.json` generation during build, it also adds a new client side hook `useAsset` which will use the generated asset manifest to lookup the hashed filename.
eg.
```ts
// In production would return something like "/styles.4h443h.css"
const styles = useAsset("/styles.css");
```
> Hash static assets

- examples/basic/src/app.tsx
- hooks/env-context.js
- hooks/use-env.js
- lib/context/env.ts
- lib/deps.ts
- lib/provider.ts
- lib/server.ts
Allows using ULTRA_PUBLIC_ prefixed environment variables. Also adds support for `.env` files to be loaded from the project root
eg
```ts
const foo = useEnv('ULTRA_PUBLIC_FOO')
```
> feat: useEnv hook

- hooks/use-async.js
- hooks/use-mounted-state.js
- test/hooks/use-async.test.tsx
The current implementation of `useAsync` returns the callback if data is not present when the component mounts, which means if the data on the server doesn't resolve and stream practically instantly, the client will return the callback - which means fetching client side. The data that gets streamed in is ignored. The idea here is that we want to start fetching on the server, and access it on the client. 
I think one approach is to have this hook always return a function that returns a promise. This makes it nicely compatible with fetching libraries and I think it's a decent API. So we can either return a promise to return the data when it streams in, or if we already have the data we can choose to either return it or return the callback.
This way, an end user can do something like this: …
> Extended useAsync functionality

- lib/deps.ts
- lib/middleware/compiler.ts
- lib/server.ts
- lib/types.ts
This PR updates Hono to the latest version 2.2.5 also changes our static routes to only use GET
> deps: updated Hono to latest version

- lib/stream.ts
Our matching logic for the closing head tag follows Next.JS.
They just commited a fix which would prevent matching something like `</header>`
So this PR replicates that
> fix: match the actual head closing tag when inserting

- lib/ultra.ts
In production, client scripts are relative to current depth, meaning they will 404 in deeply nested paths.
This should always make them absolute paths.
> fix: client entry point absolute path

- lib/build/deps.ts
- lib/build/types.ts
- lib/build/ultra.ts
- test/fixture/build.test.ts
This PR fixes #193
Mesozoic was updated to allow this feature as well as some options added to `createBuilder`.
> fix: updated mesozoic to allow bypassing the vendoring of remote dependencies

- lib/build/deps.ts
Updates mesozoic to address an issue with the browser importMap resolved paths being relative.
Should also help issues with Netlify deployment
> chore: update mesozoic

- lib/build/deps.ts
- test/fixture/build.test.ts
Fixes #221
Updated mesozoic to include a fix that when an 'ignore' pattern ends with '/' it assumes that you want to deeply ignore anything that matches that pattern.
So it essentially is doing the same as the below:
```ts
builder.ignore('./directory/**')
```
> fix: The `ignored` option is not working

- lib/create/common/content/importMap.ts
Some editors complain that the import redirects to a specific version, so specifying it, eliminates the problem.
> Specified version of wouter

- examples/ultra-website/dev.ts
- examples/ultra-website/public/service-worker.js
- examples/with-mdx/dev.ts
- examples/with-unocss/dev.ts
- lib/create/common/createUltraApp.ts
- test/fixture/build.test.ts
- tools/dev.ts
- tools/test-examples.ts
Deno.run is deprecated for https://deno.land/api@v1.33.4?s=Deno.Command
> Remove Deno.run in favor of new Deno.Command

- importMap.dev.json
- lib/middleware/compiler.ts
- lib/render.ts
- lib/stream.ts
- lib/ultra.ts
- test/fixture/importMap.json
Prefixing an importSpecifier with `@ultra/` in your importMap will now allow importing remote files that would usually require transpiling for the browser.
eg.
```jsonc
{
"imports": {
// Your other imports
"@ultra/qrcode/": "https://deno.land/x/qrcode@v2.0.0/"
}
}
```
When the importMap is injected in the HTML stream sent to the browser during dev mode, the import `https://deno.land/x/qrcode@v2.0.0/` will be rewritten to `/_ultra/compiler/https%3A%2F%2Fdeno.land%2Fx%2Fqrcode%40v2.0.0%2F/`
The compiler middleware will then fetch that remote file and transpile as if it was a local file!
> fix: support compiling remote sources in dev

- lib/context/env.ts
- lib/context/serverInsertedHtml.ts
- test/unit/use-env.test.tsx
This PR changes the env available on the client to include `ULTRA_MODE`. Also fixes an annoying warning about unique "key" prop
> fix: env doesn't include ULTRA_MODE

- .devcontainer/devcontainer.json
- deno.json
- examples/lite/app.tsx
- lib/ultra.ts
- test/fixture/client.foo.tsx
- test/fixture/server.test.ts
- test/fixture/server.tsx
This PR adds the option to override the browser entrypoint when calling `server.render`
> fix: allow overriding browser entrypoint

- lib/react/renderer.ts
- lib/renderer.ts
I believe both of those renderers exist in the scope of the server.
On in the framework-agnostic land I believe you want to narrow the rendered type to `ReadableStream`.
This typing would work as a return type for React's SSR, but I think it will be better to use their fancy `ReactDOMServerReadableStream` type.
I think it is ready for merge, running app from `./app` works and I can click the button to increment the counter.
> tech: narrow typings for refactor server handler

- .vscode/settings.json
- examples/basic/server.tsx
- lib/handler.ts
- lib/static/handler.ts
- lib/utils/import-map.ts
I've repaired the `basic` example
Ive based on branch with refactor.
Added a utility to execute and compose handlers AND added an option for handler to throw to manifest that something went wrong in controlled way.
Created static file handler and I've tried my best to make it to stream data from reader.
I am not sure if this utility for reading import file will be useful - adding it for now.
Welcome back :eyes:
> tech: revive example basic on refactor branch
